"""Build local UI web fonts from verified upstream files, without installing fonts."""
from pathlib import Path
import argparse
import hashlib
import json
import re
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source_directory', type=Path)
parser.add_argument('--python-deps', type=Path)
parser.add_argument('--role', choices=('all', 'interface', 'display', 'reading'), default='all', help='Rebuild one role while preserving the other local font assets')
args = parser.parse_args()
if args.python_deps:
    sys.path.insert(0, str(args.python_deps.resolve()))
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
destination = root / 'src/shared/fonts'
destination.mkdir(exist_ok=True)
sources = args.source_directory.resolve()
interface_files = sorted((root / 'src/settings').glob('*.ts*')) + [root / 'src/tray-menu/TrayMenu.tsx', root / 'src-tauri/src/app/tray_menu.rs']
interface_text = ''.join(p.read_text(encoding='utf-8') for p in interface_files)
interface_chars = set(map(chr, range(32, 127))) | set(re.findall(r'[\u3000-\u303f\u3400-\u9fff\uff00-\uffef]', interface_text)) | set('…—·×✓')
display_chars = set('日常翻译模型配置')
reading_chars = set('学习选择使用场景与模型思考方式结合上下文理解论文、教材与专业内容已保存')
jobs = [
    ('interface', 'TranslayInterface', sources / 'interface.ttf', interface_chars, 'a3041811a78c361b1de50f953c805e0244951c21c5bd412f7232ef0d899af0da'),
    ('display', 'TranslayDisplay', next((sources / 'smiley').rglob('SmileySans-Oblique.ttf'), None), display_chars, 'b447d7e781f08bc95c4c9f23ba71ed2b8ebb639aa7184485c71c4ca5afcd25c4'),
    ('reading', 'TranslayReading', sources / 'reading.ttf', reading_chars, 'cd1a6fa39c4ea42fd8f4e289945789b0e510cf7016435640f8893cdad9b220f3'),
]
rules = []
report = []
for role, family, source, chars, expected_sha in jobs:
    if args.role != 'all' and args.role != role:
        continue
    if source is None:
        raise ValueError(f'{role}: upstream file is missing')
    source_sha = hashlib.sha256(source.read_bytes()).hexdigest()
    if source_sha != expected_sha:
        raise ValueError(f'{role}: upstream file SHA-256 mismatch')
    font = TTFont(source)
    cmap = font.getBestCmap()
    # Decorative symbols absent upstream deliberately use the system fallback.
    if role == 'interface':
        chars = {c for c in chars if ord(c) in cmap}
    elif any(ord(c) not in cmap for c in chars):
        raise ValueError(f'{role}: missing required label glyph')
    original_name = font['name'].getDebugName(1)
    original_version = font['name'].getDebugName(5)
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_languages = ['*']
    options.name_legacy = True
    options.layout_features = ['*']
    sub = subset.Subsetter(options=options)
    sub.populate(text=''.join(sorted(chars)))
    sub.subset(font)
    # These are derived subsets; give them non-reserved internal names.
    for record in font['name'].names:
        if record.nameID in (1, 3, 4, 6, 16):
            record.string = family.encode(record.getEncoding())
    license_text = (destination / f'OFL-{role}.txt').read_text(encoding='utf-8-sig')
    font['name'].setName(license_text, 13, 3, 1, 0x409)
    font.flavor = 'woff2'
    output = destination / f'translay-{role}.woff2'
    font.save(output)
    codepoints = sorted(font.getBestCmap())
    ranges = []
    first = last = codepoints[0]
    for value in codepoints[1:]:
        if value == last + 1:
            last = value
        else:
            ranges.append(f'U+{first:X}' + (f'-{last:X}' if first != last else ''))
            first = last = value
    ranges.append(f'U+{first:X}' + (f'-{last:X}' if first != last else ''))
    weight = '100 900' if 'fvar' in font else '400'
    rules.append(f'@font-face {{\n  font-family: "{family}";\n  src: url("./fonts/translay-{role}.woff2?no-inline") format("woff2");\n  font-weight: {weight};\n  font-style: normal;\n  font-display: block;\n  unicode-range: {", ".join(ranges)};\n}}')
    report.append({'role': role, 'family': family, 'upstreamName': original_name, 'upstreamVersion': original_version, 'upstreamSHA256': source_sha, 'glyphs': len(codepoints), 'bytes': output.stat().st_size, 'sha256': hashlib.sha256(output.read_bytes()).hexdigest()})
tokens = '''
:root {
  --font-interface: "TranslayInterface", "Segoe UI Variable", "Microsoft YaHei UI", sans-serif;
  --font-display: "TranslayDisplay", "Segoe UI Variable", "Microsoft YaHei UI", sans-serif;
  --font-reading: "TranslayReading", "Microsoft YaHei UI", sans-serif;
}
'''
css_path = root / 'src/shared/uiFonts.css'
if args.role == 'all':
    css = '/* Generated by tools/subset-ui-fonts.py; local fonts only. */\n' + '\n\n'.join(rules) + '\n' + tokens
else:
    existing = json.loads((destination / 'manifest.json').read_text(encoding='utf-8'))['files']
    replacement = {item['role']: item for item in report}
    report = [replacement.get(item['role'], item) for item in existing]
    css = css_path.read_text(encoding='utf-8')
    family = replacement[args.role]['family']
    pattern = r'@font-face\s*\{[^}]*font-family:\s*"' + re.escape(family) + r'"[^}]*\}'
    if len(re.findall(pattern, css)) != 1:
        raise ValueError(f'{args.role}: expected exactly one existing font-face rule')
    css = re.sub(pattern, lambda _: rules[0], css)
css_path.write_text(css, encoding='utf-8')
(destination / 'manifest.json').write_text(json.dumps({'fontTools': '4.66.1', 'brotli': '1.2.0', 'files': report}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(json.dumps({'totalBytes': sum(item['bytes'] for item in report), 'fonts': report}, ensure_ascii=False))
